services:
  - type: web
    name: sgeplus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
