"""remove components_config

Revision ID: 069d44ad43cf
Revises: a9e34ec47343
Create Date: 2026-06-08 13:57:09.673991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069d44ad43cf'
down_revision = 'a9e34ec47343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_column('components_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('components_config', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
