"""Add student/professor fields and roles

Revision ID: 15acbe5a2e4e
Revises: 3386fc65facc
Create Date: 2026-02-05 13:38:26.493478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15acbe5a2e4e'
down_revision = '3386fc65facc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('race', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('professor_subjects',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'subject_id')
    )
    op.create_table('professor_classes',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'class_id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('race', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_student_cpf', ['cpf'])
        batch_op.create_foreign_key('fk_student_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('roles')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_student_cpf', type_='unique')
        batch_op.drop_column('user_id')
        batch_op.drop_column('race')
        batch_op.drop_column('sex')
        batch_op.drop_column('cpf')

    op.drop_table('professor_classes')
    op.drop_table('professor_subjects')
    op.drop_table('professor')
    # ### end Alembic commands ###
