"""add authorized_by to exam

Revision ID: 1a4543ccedc9
Revises: 7fda7b644fbc
Create Date: 2026-02-08 20:05:22.433405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4543ccedc9'
down_revision = '7fda7b644fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorized_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_exam_authorized_by_id_user'), 'user', ['authorized_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_exam_authorized_by_id_user'), type_='foreignkey')
        batch_op.drop_column('authorized_by_id')

    # ### end Alembic commands ###
