"""Add Ombudsman models

Revision ID: 25ccdd0ef708
Revises: be037be66c85
Create Date: 2026-06-23 15:25:55.506828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ccdd0ef708'
down_revision = 'be037be66c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ombudsman_nature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ombudsman_nature_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ombudsman_nature')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_ombudsman_nature_tenant_name')
    )
    op.create_table('ombudsman_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('nature_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['nature_id'], ['ombudsman_nature.id'], name=op.f('fk_ombudsman_subject_nature_id_ombudsman_nature')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ombudsman_subject_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ombudsman_subject')),
    sa.UniqueConstraint('tenant_id', 'nature_id', 'name', name='uq_ombudsman_subject_tenant_nature_name')
    )
    op.create_table('ombudsman_manifestation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('protocol_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('nature_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('requester_email', sa.String(length=120), nullable=False),
    sa.Column('requester_phone', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], name=op.f('fk_ombudsman_manifestation_assigned_to_id_user')),
    sa.ForeignKeyConstraint(['nature_id'], ['ombudsman_nature.id'], name=op.f('fk_ombudsman_manifestation_nature_id_ombudsman_nature')),
    sa.ForeignKeyConstraint(['subject_id'], ['ombudsman_subject.id'], name=op.f('fk_ombudsman_manifestation_subject_id_ombudsman_subject')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ombudsman_manifestation_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ombudsman_manifestation')),
    sa.UniqueConstraint('protocol_number', name=op.f('uq_ombudsman_manifestation_protocol_number'))
    )
    op.create_table('ombudsman_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifestation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manifestation_id'], ['ombudsman_manifestation.id'], name=op.f('fk_ombudsman_history_manifestation_id_ombudsman_manifestation')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ombudsman_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ombudsman_history'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ombudsman_history')
    op.drop_table('ombudsman_manifestation')
    op.drop_table('ombudsman_subject')
    op.drop_table('ombudsman_nature')
    # ### end Alembic commands ###
