"""add new fields to teaching unit

Revision ID: 2a7778eb857c
Revises: 3bd4446dda3b
Create Date: 2026-05-30 15:40:08.764962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7778eb857c'
down_revision = '3bd4446dda3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inep_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('residential_zone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('differentiated_location', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_unit', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('differentiated_location')
        batch_op.drop_column('residential_zone')
        batch_op.drop_column('municipio')
        batch_op.drop_column('uf')
        batch_op.drop_column('inep_code')

    # ### end Alembic commands ###
