"""Add subject and school year to Exam

Revision ID: 2fdfb3af816c
Revises: 7e3d87b8b3e1
Create Date: 2026-02-08 21:50:52.878110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdfb3af816c'
down_revision = '7e3d87b8b3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('school_year_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_exam_school_year_id_school_year'), 'school_year', ['school_year_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_exam_subject_id_subject'), 'subject', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_exam_subject_id_subject'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_exam_school_year_id_school_year'), type_='foreignkey')
        batch_op.drop_column('school_year_id')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
