"""add_descriptor_type

Revision ID: 322b35a2cef4
Revises: 46a8f2ef7fad
Create Date: 2026-02-05 16:55:06.511064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322b35a2cef4'
down_revision = '46a8f2ef7fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptor', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
