"""Add map_url to Tenant

Revision ID: 37379620fbb8
Revises: d8995797900b
Create Date: 2026-06-04 16:59:16.081838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37379620fbb8'
down_revision = 'd8995797900b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('map_url')

    # ### end Alembic commands ###
