"""Add contracts module

Revision ID: 43088307f307
Revises: aab2166af1e9
Create Date: 2026-06-26 12:55:00.325839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43088307f307'
down_revision = 'aab2166af1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_contract_category_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_category'))
    )
    op.create_table('financial_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_financial_program_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_program'))
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('ALIMENTACAO_ESCOLAR', 'SERVICOS', 'GERAL_OUTROS', name='contractpurposeenum'), nullable=False),
    sa.Column('modality', sa.Enum('CONCORRENCIA_LICITACAO', 'PREGAO', 'CARTA_CONVITE', 'DISPENSA_LICITACAO', 'REGISTRO_PRECO', name='contractmodalityenum'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('signature_date', sa.Date(), nullable=False),
    sa.Column('validity_start', sa.Date(), nullable=False),
    sa.Column('validity_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['contract_category.id'], name=op.f('fk_contract_category_id_contract_category')),
    sa.ForeignKeyConstraint(['program_id'], ['financial_program.id'], name=op.f('fk_contract_program_id_financial_program')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_contract_supplier_id_supplier')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_contract_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract'))
    )
    op.create_table('contract_services',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_contract_services_contract_id_contract')),
    sa.ForeignKeyConstraint(['service_id'], ['service_type.id'], name=op.f('fk_contract_services_service_id_service_type')),
    sa.PrimaryKeyConstraint('contract_id', 'service_id', name=op.f('pk_contract_services'))
    )
    with op.batch_alter_table('ombudsman_manifestation', schema=None) as batch_op:
        batch_op.alter_column('nature',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('RECLAMACAO', 'ELOGIO', 'SOLICITACAO', 'SUGESTAO', 'DENUNCIA', name='ombudsmannatureenum'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('PENDENTE', 'ACEITA', 'REJEITADA', 'TRAMITANDO', 'RESOLVIDA', name='ombudsmanstatusenum'),
               existing_nullable=False)
        batch_op.alter_column('requester_type',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('ALUNO', 'SERVIDOR', 'RESPONSAVEL_ALUNO', 'OUTRO', name='ombudsmanrequestertypeenum'),
               existing_nullable=False)
        batch_op.alter_column('entry_mode',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('PORTAL_DA_COMUNIDADE', 'EMAIL', 'WHATSAPP', 'PORTAL_DO_ALUNO', 'APLICATIVO', 'TELEFONE', 'PRESENCIAL', 'CALL_CENTER', name='ombudsmanentrymodeenum'),
               existing_nullable=False)

    with op.batch_alter_table('ombudsman_subject', schema=None) as batch_op:
        batch_op.alter_column('nature',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('RECLAMACAO', 'ELOGIO', 'SOLICITACAO', 'SUGESTAO', 'DENUNCIA', name='ombudsmannatureenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ombudsman_subject', schema=None) as batch_op:
        batch_op.alter_column('nature',
               existing_type=sa.Enum('RECLAMACAO', 'ELOGIO', 'SOLICITACAO', 'SUGESTAO', 'DENUNCIA', name='ombudsmannatureenum'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('ombudsman_manifestation', schema=None) as batch_op:
        batch_op.alter_column('entry_mode',
               existing_type=sa.Enum('PORTAL_DA_COMUNIDADE', 'EMAIL', 'WHATSAPP', 'PORTAL_DO_ALUNO', 'APLICATIVO', 'TELEFONE', 'PRESENCIAL', 'CALL_CENTER', name='ombudsmanentrymodeenum'),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('requester_type',
               existing_type=sa.Enum('ALUNO', 'SERVIDOR', 'RESPONSAVEL_ALUNO', 'OUTRO', name='ombudsmanrequestertypeenum'),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDENTE', 'ACEITA', 'REJEITADA', 'TRAMITANDO', 'RESOLVIDA', name='ombudsmanstatusenum'),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('nature',
               existing_type=sa.Enum('RECLAMACAO', 'ELOGIO', 'SOLICITACAO', 'SUGESTAO', 'DENUNCIA', name='ombudsmannatureenum'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('contract_services')
    op.drop_table('contract')
    op.drop_table('financial_program')
    op.drop_table('contract_category')
    # ### end Alembic commands ###
