"""Added DietaryRestriction

Revision ID: 459c578c6703
Revises: 8f74a2d1b51e
Create Date: 2026-03-26 17:53:58.288321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459c578c6703'
down_revision = '8f74a2d1b51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietary_restriction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dietary_restriction')),
    sa.UniqueConstraint('name', name=op.f('uq_dietary_restriction_name'))
    )
    op.create_table('student_dietary_restrictions',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('dietary_restriction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dietary_restriction_id'], ['dietary_restriction.id'], name=op.f('fk_student_dietary_restrictions_dietary_restriction_id_dietary_restriction')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_dietary_restrictions_student_id_student')),
    sa.PrimaryKeyConstraint('student_id', 'dietary_restriction_id', name=op.f('pk_student_dietary_restrictions'))
    )
    with op.batch_alter_table('absence_reason', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(batch_op.f('uq_absence_reason_name'), ['name'])

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('exclude_special_needs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_special_needs', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))

    with op.batch_alter_table('absence_reason', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_absence_reason_name'), type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('student_dietary_restrictions')
    op.drop_table('dietary_restriction')
    # ### end Alembic commands ###
