"""Add exam_classes table

Revision ID: 4734fe6fb1ff
Revises: 1a4543ccedc9
Create Date: 2026-02-08 20:49:51.295183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4734fe6fb1ff'
down_revision = '1a4543ccedc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_classes',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_exam_classes_class_id_class')),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_exam_classes_exam_id_exam')),
    sa.PrimaryKeyConstraint('exam_id', 'class_id', name=op.f('pk_exam_classes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_classes')
    # ### end Alembic commands ###
