"""Added LMS Phase 3 models

Revision ID: 4824e0cd9d98
Revises: 913965b33b65
Create Date: 2026-08-02 12:52:45.761762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4824e0cd9d98'
down_revision = '913965b33b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('DIAGNOSTICA', 'PROCESSUAL', 'SAIDA', 'INDIFERENTE', name='lmsevaluationtypeenum'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['lms_subject.id'], name=op.f('fk_lms_evaluation_subject_id_lms_subject')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_evaluation_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_evaluation'))
    )
    op.create_table('lms_import_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['lms_evaluation.id'], name=op.f('fk_lms_import_job_evaluation_id_lms_evaluation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_import_job_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_import_job'))
    )
    op.create_table('lms_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['lms_evaluation.id'], name=op.f('fk_lms_question_evaluation_id_lms_evaluation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_question_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_question'))
    )
    op.create_table('lms_student_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['lms_evaluation.id'], name=op.f('fk_lms_student_grade_evaluation_id_lms_evaluation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_lms_student_grade_student_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_student_grade_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_student_grade'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lms_student_grade')
    op.drop_table('lms_question')
    op.drop_table('lms_import_job')
    op.drop_table('lms_evaluation')
    # ### end Alembic commands ###
