"""Add scoring fields to Exam and demographic fields to Student

Revision ID: 4dfc25290d34
Revises: 2fdfb3af816c
Create Date: 2026-02-09 09:23:15.208453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfc25290d34'
down_revision = '2fdfb3af816c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoring_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_value', sa.Float(), nullable=True))

    with op.batch_alter_table('exam_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('family_income', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('family_income')
        batch_op.drop_column('nationality')

    with op.batch_alter_table('exam_item', schema=None) as batch_op:
        batch_op.drop_column('value')

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('total_value')
        batch_op.drop_column('scoring_type')

    # ### end Alembic commands ###
