"""refactor to enums

Revision ID: 4e8b5ed5641a
Revises: 9a48324d84c5
Create Date: 2026-06-25 08:08:31.416393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8b5ed5641a'
down_revision = '9a48324d84c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('ombudsman_manifestation', schema=None) as batch_op:
        batch_op.alter_column('nature', nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('requester_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('entry_mode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_ombudsman_manifestation_nature_id_ombudsman_nature'), type_='foreignkey')
        batch_op.drop_column('nature_id')

    with op.batch_alter_table('ombudsman_subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nature', sa.Integer(), nullable=True))

    op.execute('UPDATE ombudsman_subject SET nature = nature_id')

    with op.batch_alter_table('ombudsman_subject', schema=None) as batch_op:
        batch_op.alter_column('nature', nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_ombudsman_subject_tenant_nature_name'), type_='unique')
        batch_op.create_unique_constraint('uq_ombudsman_subject_tenant_nature_name', ['tenant_id', 'nature', 'name'])
        batch_op.drop_constraint(batch_op.f('fk_ombudsman_subject_nature_id_ombudsman_nature'), type_='foreignkey')
        batch_op.drop_column('nature_id')

    op.drop_table('ombudsman_nature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ombudsman_subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nature_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_ombudsman_subject_nature_id_ombudsman_nature'), 'ombudsman_nature', ['nature_id'], ['id'])
        batch_op.drop_constraint('uq_ombudsman_subject_tenant_nature_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_ombudsman_subject_tenant_nature_name'), ['tenant_id', 'nature_id', 'name'])
        batch_op.drop_column('nature')

    with op.batch_alter_table('ombudsman_manifestation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nature_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_ombudsman_manifestation_nature_id_ombudsman_nature'), 'ombudsman_nature', ['nature_id'], ['id'])
        batch_op.alter_column('entry_mode',
               existing_type=sa.Enum('PORTAL_DA_COMUNIDADE', 'EMAIL', 'WHATSAPP', 'PORTAL_DO_ALUNO', 'APLICATIVO', 'TELEFONE', 'PRESENCIAL', 'CALL_CENTER', name='ombudsmanentrymodeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('requester_type',
               existing_type=sa.Enum('ALUNO', 'SERVIDOR', 'RESPONSAVEL_ALUNO', 'OUTRO', name='ombudsmanrequestertypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDENTE', 'ACEITA', 'REJEITADA', 'TRAMITANDO', 'RESOLVIDA', name='ombudsmanstatusenum'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('nature')

    op.create_table('ombudsman_nature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ombudsman_nature_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ombudsman_nature')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_ombudsman_nature_tenant_name'))
    )
    # ### end Alembic commands ###
