"""Fix AbsenceReason unique constraint

Revision ID: 534ca591859d
Revises: a361e4ff25e9
Create Date: 2026-06-02 15:32:12.692471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534ca591859d'
down_revision = 'a361e4ff25e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence_reason', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_absence_reason_name'), type_='unique')
        batch_op.create_unique_constraint('uq_absence_reason_tenant_name', ['tenant_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence_reason', schema=None) as batch_op:
        batch_op.drop_constraint('uq_absence_reason_tenant_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_absence_reason_name'), ['name'])

    # ### end Alembic commands ###
