"""Added LMS models Phase 1

Revision ID: 562eb378d077
Revises: cc8dd0f8fcd4
Create Date: 2026-08-02 12:11:22.025350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562eb378d077'
down_revision = 'cc8dd0f8fcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_category_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_category'))
    )
    op.create_table('lms_category_coordinators',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lms_category.id'], name=op.f('fk_lms_category_coordinators_category_id_lms_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lms_category_coordinators_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'user_id', name=op.f('pk_lms_category_coordinators'))
    )
    op.create_table('lms_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description_brief', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subscribe_begin', sa.Date(), nullable=False),
    sa.Column('subscribe_end', sa.Date(), nullable=False),
    sa.Column('init_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('display_avatar', sa.Boolean(), nullable=True),
    sa.Column('external_access', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['lms_category.id'], name=op.f('fk_lms_subject_category_id_lms_category')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_subject_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_subject'))
    )
    op.create_table('lms_student_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['lms_subject.id'], name=op.f('fk_lms_student_group_subject_id_lms_subject')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_student_group_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_student_group'))
    )
    op.create_table('lms_subject_professors',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['lms_subject.id'], name=op.f('fk_lms_subject_professors_subject_id_lms_subject'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lms_subject_professors_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'user_id', name=op.f('pk_lms_subject_professors'))
    )
    op.create_table('lms_subject_students',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['lms_subject.id'], name=op.f('fk_lms_subject_students_subject_id_lms_subject'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lms_subject_students_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'user_id', name=op.f('pk_lms_subject_students'))
    )
    op.create_table('lms_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['lms_subject.id'], name=op.f('fk_lms_topic_subject_id_lms_subject')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_topic_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_topic'))
    )
    op.create_table('lms_student_group_participants',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['lms_student_group.id'], name=op.f('fk_lms_student_group_participants_group_id_lms_student_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lms_student_group_participants_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_lms_student_group_participants'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('social_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('show_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('image_path')
        batch_op.drop_column('show_email')
        batch_op.drop_column('social_name')
        batch_op.drop_column('last_name')

    op.drop_table('lms_student_group_participants')
    op.drop_table('lms_topic')
    op.drop_table('lms_subject_students')
    op.drop_table('lms_subject_professors')
    op.drop_table('lms_student_group')
    op.drop_table('lms_subject')
    op.drop_table('lms_category_coordinators')
    op.drop_table('lms_category')
    # ### end Alembic commands ###
