"""Add school_year and subject to descriptor

Revision ID: 61b6568823de
Revises: a88698f75640
Create Date: 2026-02-03 08:10:15.820028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b6568823de'
down_revision = 'a88698f75640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_legacy', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('school_year_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        # batch_op.drop_index(batch_op.f('ix_descriptor_code')) # Already dropped in previous migration potentially? But might be safer to comment out if it fails, or keep naming logic.
        # However, the previous migration dropped it. Alembic autogenerate sees it gone, so it adds it again here? No, autogenerate compares models vs DB.
        # If DB still has it (because previous mig failed partly?), then this is correct.
        # But let's name the FKs as required by SQLite batch ops.
        batch_op.create_foreign_key('fk_descriptor_subject_id', 'subject', ['subject_id'], ['id'])
        batch_op.create_foreign_key('fk_descriptor_school_year_id', 'school_year', ['school_year_id'], ['id'])
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('fk_descriptor_school_year_id', type_='foreignkey')
        batch_op.drop_constraint('fk_descriptor_subject_id', type_='foreignkey')
        # batch_op.create_index(batch_op.f('ix_descriptor_code'), ['code'], unique=1)
        batch_op.drop_column('subject_id')
        batch_op.drop_column('school_year_id')
        batch_op.drop_column('subject_legacy')

    # ### end Alembic commands ###
