"""add ombudsman attachments

Revision ID: 6295301229c7
Revises: 25ccdd0ef708
Create Date: 2026-06-24 20:51:22.034215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6295301229c7'
down_revision = '25ccdd0ef708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ombudsman_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifestation_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manifestation_id'], ['ombudsman_manifestation.id'], name=op.f('fk_ombudsman_attachment_manifestation_id_ombudsman_manifestation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ombudsman_attachment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ombudsman_attachment')
    # ### end Alembic commands ###
