"""Add director fields to TeachingUnit

Revision ID: 684e28563fc9
Revises: 77b5e65e1a69
Create Date: 2026-08-21 09:59:59.704391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684e28563fc9'
down_revision = '77b5e65e1a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('modulation_start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_unit', schema=None) as batch_op:
        batch_op.drop_column('modulation_start_date')
        batch_op.drop_column('director_name')

    # ### end Alembic commands ###
