"""Add service order models

Revision ID: 6cbd5f562d21
Revises: 069d44ad43cf
Create Date: 2026-06-17 19:43:07.414973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbd5f562d21'
down_revision = '069d44ad43cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_service_type_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_type')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_service_type_tenant_name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=2), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_supplier_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier')),
    sa.UniqueConstraint('tenant_id', 'cpf_cnpj', name='uq_supplier_tenant_cpf_cnpj')
    )
    op.create_table('supplier_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_contact_supplier_id_supplier')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_supplier_contact_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_contact'))
    )
    op.create_table('service_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_service_order_created_by_id_user')),
    sa.ForeignKeyConstraint(['school_id'], ['teaching_unit.id'], name=op.f('fk_service_order_school_id_teaching_unit')),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], name=op.f('fk_service_order_service_type_id_service_type')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_service_order_supplier_id_supplier')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_service_order_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order'))
    )
    op.create_table('service_order_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_order.id'], name=op.f('fk_service_order_attachment_service_order_id_service_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_attachment'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    op.drop_table('service_order_attachment')
    op.drop_table('service_order')
    op.drop_table('supplier_contact')
    op.drop_table('supplier')
    op.drop_table('service_type')
    # ### end Alembic commands ###
