"""Add new student fields

Revision ID: 76c14b35ed13
Revises: d2213f516b37
Create Date: 2026-03-26 21:21:16.111777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c14b35ed13'
down_revision = 'd2213f516b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inep_code', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('sus_card', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('bolsa_familia', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('birth_state', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('birth_city_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('residential_zone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('differentiated_location', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_student_birth_city_id_city'), 'city', ['birth_city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_birth_city_id_city'), type_='foreignkey')
        batch_op.drop_column('differentiated_location')
        batch_op.drop_column('residential_zone')
        batch_op.drop_column('birth_city_id')
        batch_op.drop_column('birth_state')
        batch_op.drop_column('bolsa_familia')
        batch_op.drop_column('sus_card')
        batch_op.drop_column('inep_code')

    # ### end Alembic commands ###
