"""add attendance fields

Revision ID: 77b5e65e1a69
Revises: 4824e0cd9d98
Create Date: 2026-08-07 13:15:51.976113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b5e65e1a69'
down_revision = '4824e0cd9d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subject_attendance', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_result', schema=None) as batch_op:
        batch_op.drop_column('subject_attendance')
        batch_op.drop_column('attendance_percentage')

    # ### end Alembic commands ###
