"""Add academic management tables

Revision ID: 7cb34438aac0
Revises: ba5081a58fb8
Create Date: 2026-02-02 22:26:28.136863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb34438aac0'
down_revision = 'ba5081a58fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teaching_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['teaching_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('teaching_unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_year.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['curriculum_structure.id'], ),
    sa.ForeignKeyConstraint(['teaching_unit_id'], ['teaching_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_subjects',
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum_structure.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('curriculum_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curriculum_subjects')
    op.drop_table('class')
    op.drop_table('curriculum_structure')
    op.drop_table('teaching_unit')
    op.drop_table('subject')
    op.drop_table('school_year')
    # ### end Alembic commands ###
