"""Add allow_teacher_entry to Exam

Revision ID: 7e3d87b8b3e1
Revises: 4734fe6fb1ff
Create Date: 2026-02-08 20:57:36.694261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3d87b8b3e1'
down_revision = '4734fe6fb1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_teacher_entry', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('allow_teacher_entry')

    # ### end Alembic commands ###
