"""add alu_frequencia

Revision ID: 81f7a4e63d81
Revises: 3bb599da4693
Create Date: 2026-10-06 10:03:37.314202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f7a4e63d81'
down_revision = '3bb599da4693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_evaluation_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alu_frequencia', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_evaluation_student', schema=None) as batch_op:
        batch_op.drop_column('alu_frequencia')

    # ### end Alembic commands ###
