"""add partner_institution

Revision ID: 8d0fe4383b3f
Revises: d550aed4cc4d
Create Date: 2026-09-30 12:09:13.625377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0fe4383b3f'
down_revision = 'd550aed4cc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_partner_institution_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_institution'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_institution')
    # ### end Alembic commands ###
