"""empty message

Revision ID: 8f74a2d1b51e
Revises: 4dfc25290d34
Create Date: 2026-02-09 16:11:07.167988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f74a2d1b51e'
down_revision = '4dfc25290d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_absence_reason')),
    sa.UniqueConstraint('name', name=op.f('uq_absence_reason_name'))
    )
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_nationality', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('exclude_special_needs', sa.Boolean(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_needs', sa.Boolean(), nullable=True))

    with op.batch_alter_table('student_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absence_reason_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_student_result_absence_reason_id_absence_reason'), 'absence_reason', ['absence_reason_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_result', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_result_absence_reason_id_absence_reason'), type_='foreignkey')
        batch_op.drop_column('absence_reason_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('special_needs')

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('exclude_special_needs')
        batch_op.drop_column('target_nationality')

    op.drop_table('absence_reason')
    # ### end Alembic commands ###
