"""Added LMS Phase 2 models

Revision ID: 913965b33b65
Revises: 562eb378d077
Create Date: 2026-08-02 12:28:39.796356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913965b33b65'
down_revision = '562eb378d077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('presentation', sa.Text(), nullable=False),
    sa.Column('init_date', sa.DateTime(), nullable=False),
    sa.Column('limit_submission_date', sa.DateTime(), nullable=False),
    sa.Column('brief_description', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['lms_subject.id'], name=op.f('fk_lms_goal_subject_id_lms_subject')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_goal_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_goal'))
    )
    op.create_table('lms_goal_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('ref_value', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['lms_goal.id'], name=op.f('fk_lms_goal_item_goal_id_lms_goal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_goal_item_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_goal_item'))
    )
    op.create_table('lms_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('HTML', 'YOUTUBE', 'FILE', 'PDF', 'LINK', name='lmsresourcetypeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('brief_description', sa.Text(), nullable=True),
    sa.Column('show_window', sa.Boolean(), nullable=True),
    sa.Column('all_students', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_resource_tenant_id_tenant')),
    sa.ForeignKeyConstraint(['topic_id'], ['lms_topic.id'], name=op.f('fk_lms_resource_topic_id_lms_topic')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_resource'))
    )
    op.create_table('lms_mural_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('COMMENT', 'HELP', name='lmsmuralactionenum'), nullable=False),
    sa.Column('post', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_lms_mural_post_author_id_user')),
    sa.ForeignKeyConstraint(['resource_id'], ['lms_resource.id'], name=op.f('fk_lms_mural_post_resource_id_lms_resource')),
    sa.ForeignKeyConstraint(['subject_id'], ['lms_subject.id'], name=op.f('fk_lms_mural_post_subject_id_lms_subject')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_mural_post_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_mural_post'))
    )
    op.create_table('lms_resource_groups',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['lms_student_group.id'], name=op.f('fk_lms_resource_groups_group_id_lms_student_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['lms_resource.id'], name=op.f('fk_lms_resource_groups_resource_id_lms_resource'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'group_id', name=op.f('pk_lms_resource_groups'))
    )
    op.create_table('lms_resource_students',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['lms_resource.id'], name=op.f('fk_lms_resource_students_resource_id_lms_resource'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lms_resource_students_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'user_id', name=op.f('pk_lms_resource_students'))
    )
    op.create_table('lms_mural_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_lms_mural_comment_author_id_user')),
    sa.ForeignKeyConstraint(['post_id'], ['lms_mural_post.id'], name=op.f('fk_lms_mural_comment_post_id_lms_mural_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_lms_mural_comment_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lms_mural_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lms_mural_comment')
    op.drop_table('lms_resource_students')
    op.drop_table('lms_resource_groups')
    op.drop_table('lms_mural_post')
    op.drop_table('lms_resource')
    op.drop_table('lms_goal_item')
    op.drop_table('lms_goal')
    # ### end Alembic commands ###
