"""Add Country table

Revision ID: 97a7235a89b8
Revises: 8342d1911f77
Create Date: 2026-03-26 21:42:54.669524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a7235a89b8'
down_revision = '8342d1911f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ibge_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country')),
    sa.UniqueConstraint('ibge_code', name=op.f('uq_country_ibge_code'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
