"""add ombudsman requester_type and entry_mode

Revision ID: 9a48324d84c5
Revises: 6295301229c7
Create Date: 2026-06-24 21:01:48.721285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a48324d84c5'
down_revision = '6295301229c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ombudsman_manifestation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('entry_mode', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ombudsman_manifestation', schema=None) as batch_op:
        batch_op.drop_column('entry_mode')
        batch_op.drop_column('requester_type')

    # ### end Alembic commands ###
