"""add exam academic year and date

Revision ID: 9ae8cf779831
Revises: a2b7a3f5d625
Create Date: 2026-02-07 13:51:53.283492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae8cf779831'
down_revision = 'a2b7a3f5d625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.String(length=9), nullable=False))
        batch_op.add_column(sa.Column('application_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('application_date')
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###
