"""Update SchoolYear and Subject uniqueness to be tenant scoped

Revision ID: a361e4ff25e9
Revises: 2a7778eb857c
Create Date: 2026-06-01 17:13:09.908575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a361e4ff25e9'
down_revision = '2a7778eb857c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_year', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_school_year_name'), type_='unique')
        batch_op.create_unique_constraint('uq_school_year_tenant_name', ['tenant_id', 'name'])

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subject_name'), type_='unique')
        batch_op.create_unique_constraint('uq_subject_tenant_name', ['tenant_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subject_tenant_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_subject_name'), ['name'])

    with op.batch_alter_table('school_year', schema=None) as batch_op:
        batch_op.drop_constraint('uq_school_year_tenant_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_school_year_name'), ['name'])

    # ### end Alembic commands ###
