"""Add reference matrices

Revision ID: a88698f75640
Revises: be1e3d2359d2
Create Date: 2026-02-02 23:07:39.431216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88698f75640'
down_revision = 'be1e3d2359d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('descriptor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matrix_id', sa.Integer(), nullable=True))
        # batch_op.drop_index(batch_op.f('ix_descriptor_code')) # This was unique, leaving checking it might be needed if we want to remove uniqueness
        # NOTE: drop_index might fail if it wasn't named properly before, but Alembic usually handles .f() for indices it created.
        # But let's name the FK.
        batch_op.create_foreign_key('fk_descriptor_matrix_id', 'reference_matrix', ['matrix_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_descriptor_matrix_id', type_='foreignkey')
        # batch_op.create_index(batch_op.f('ix_descriptor_code'), ['code'], unique=1)
        batch_op.drop_column('matrix_id')

    op.drop_table('reference_matrix')
    # ### end Alembic commands ###
