"""Add is_private to OmbudsmanHistory

Revision ID: aab2166af1e9
Revises: 4e8b5ed5641a
Create Date: 2026-06-25 18:14:54.593828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab2166af1e9'
down_revision = '4e8b5ed5641a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ombudsman_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ombudsman_history', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
