"""add exam scoping and recreate student result

Revision ID: ab2882ce2eaa
Revises: 9ae8cf779831
Create Date: 2026-02-07 14:00:40.052736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2882ce2eaa'
down_revision = '9ae8cf779831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('score_percentage', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_student_result_exam_id_exam')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_result_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_result'))
    )
    op.drop_table('_alembic_tmp_exam')
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regional_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teaching_unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_exam_regional_id_teaching_unit'), 'teaching_unit', ['regional_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_exam_teaching_unit_id_teaching_unit'), 'teaching_unit', ['teaching_unit_id'], ['id'])

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_professor_cpf'), ['cpf'])

    with op.batch_alter_table('school_year', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_school_year_name'), ['name'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_student_registration_number'), ['registration_number'])

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subject_name'), ['name'])

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_system_config_key'), ['key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_system_config_key'), type_='unique')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subject_name'), type_='unique')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_registration_number'), type_='unique')

    with op.batch_alter_table('school_year', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_school_year_name'), type_='unique')

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_professor_cpf'), type_='unique')

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_exam_teaching_unit_id_teaching_unit'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_exam_regional_id_teaching_unit'), type_='foreignkey')
        batch_op.drop_column('teaching_unit_id')
        batch_op.drop_column('regional_id')

    op.create_table('_alembic_tmp_exam',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=9), nullable=False),
    sa.Column('application_date', sa.DATE(), nullable=False),
    sa.Column('regional_id', sa.INTEGER(), nullable=True),
    sa.Column('teaching_unit_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['regional_id'], ['teaching_unit.id'], name=op.f('fk_exam_regional_id_teaching_unit')),
    sa.ForeignKeyConstraint(['teaching_unit_id'], ['teaching_unit.id'], name=op.f('fk_exam_teaching_unit_id_teaching_unit')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_result')
    # ### end Alembic commands ###
