"""add active field to dietary restrictions

Revision ID: b715ea7ae17a
Revises: 459c578c6703
Create Date: 2026-03-26 18:15:19.962641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b715ea7ae17a'
down_revision = '459c578c6703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dietary_restriction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dietary_restriction', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
