"""add themes

Revision ID: b7eeb4a32ab9
Revises: 61b6568823de
Create Date: 2026-02-04 12:18:18.376905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7eeb4a32ab9'
down_revision = '61b6568823de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matrix_id'], ['reference_matrix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('descriptor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_descriptor_code'))
        batch_op.create_foreign_key('fk_descriptor_theme_id', 'theme', ['theme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_descriptor_theme_id', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_descriptor_code'), ['code'], unique=1)
        batch_op.drop_column('theme_id')

    op.drop_table('theme')
    # ### end Alembic commands ###
