"""add_service_professional

Revision ID: be037be66c85
Revises: 6cbd5f562d21
Create Date: 2026-06-18 11:21:44.485284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be037be66c85'
down_revision = '6cbd5f562d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_professional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=128), nullable=True),
    sa.Column('bairro', sa.String(length=128), nullable=True),
    sa.Column('cidade', sa.String(length=128), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_service_professional_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_professional')),
    sa.UniqueConstraint('tenant_id', 'cpf', name='uq_service_professional_tenant_cpf')
    )
    op.create_table('professional_services',
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['service_professional.id'], name=op.f('fk_professional_services_professional_id_service_professional')),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], name=op.f('fk_professional_services_service_type_id_service_type')),
    sa.PrimaryKeyConstraint('professional_id', 'service_type_id', name=op.f('pk_professional_services'))
    )
    with op.batch_alter_table('service_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_service_order_professional_id_service_professional'), 'service_professional', ['professional_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_service_order_professional_id_service_professional'), type_='foreignkey')
        batch_op.drop_column('professional_id')

    op.drop_table('professional_services')
    op.drop_table('service_professional')
    # ### end Alembic commands ###
