"""add creator to questions

Revision ID: c93c7227e77e
Revises: ab2882ce2eaa
Create Date: 2026-02-07 16:31:59.918125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93c7227e77e'
down_revision = 'ab2882ce2eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_created_by_id_user'), 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_created_by_id_user'), type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
