"""Add City table

Revision ID: d2213f516b37
Revises: b715ea7ae17a
Create Date: 2026-03-26 21:10:40.599717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2213f516b37'
down_revision = 'b715ea7ae17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ibge_code', sa.String(length=20), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city')),
    sa.UniqueConstraint('ibge_code', name=op.f('uq_city_ibge_code'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
