"""Add coordinator fields to TeachingUnit

Revision ID: d550aed4cc4d
Revises: 684e28563fc9
Create Date: 2026-08-21 10:07:52.068218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd550aed4cc4d'
down_revision = '684e28563fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('coordinator_modulation_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_unit', schema=None) as batch_op:
        batch_op.drop_column('coordinator_modulation_date')
        batch_op.drop_column('coordinator_name')

    # ### end Alembic commands ###
