"""Added Quilombola and Indigenous tracking

Revision ID: d8995797900b
Revises: 534ca591859d
Create Date: 2026-06-03 17:52:07.840962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8995797900b'
down_revision = '534ca591859d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indigenous_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_indigenous_people_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indigenous_people'))
    )
    op.create_table('quilombola_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_quilombola_community_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quilombola_community'))
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quilombola', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quilombola_community_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('indigenous_people_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_student_indigenous_people_id_indigenous_people'), 'indigenous_people', ['indigenous_people_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_student_quilombola_community_id_quilombola_community'), 'quilombola_community', ['quilombola_community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_quilombola_community_id_quilombola_community'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_student_indigenous_people_id_indigenous_people'), type_='foreignkey')
        batch_op.drop_column('indigenous_people_id')
        batch_op.drop_column('quilombola_community_id')
        batch_op.drop_column('is_quilombola')

    op.drop_table('quilombola_community')
    op.drop_table('indigenous_people')
    # ### end Alembic commands ###
