"""add status and approval to questions

Revision ID: e232a0487612
Revises: c93c7227e77e
Create Date: 2026-02-07 16:53:59.885396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e232a0487612'
down_revision = 'c93c7227e77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('approved_by_secretaria', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('approved_by_secretaria')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
