"""add school domains

Revision ID: f09b880d3441
Revises: 37379620fbb8
Create Date: 2026-06-08 07:58:38.945515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09b880d3441'
down_revision = '37379620fbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electrical_energy_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_electrical_energy_source_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electrical_energy_source'))
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_region_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region'))
    )
    op.create_table('school_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_school_classification_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_classification'))
    )
    op.create_table('sub_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_sub_region_region_id_region')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_sub_region_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_region'))
    )
    with op.batch_alter_table('teaching_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('energy_source_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sub_region_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_teaching_unit_energy_source_id_electrical_energy_source'), 'electrical_energy_source', ['energy_source_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_teaching_unit_region_id_region'), 'region', ['region_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_teaching_unit_sub_region_id_sub_region'), 'sub_region', ['sub_region_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_teaching_unit_classification_id_school_classification'), 'school_classification', ['classification_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_unit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teaching_unit_classification_id_school_classification'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teaching_unit_sub_region_id_sub_region'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teaching_unit_region_id_region'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teaching_unit_energy_source_id_electrical_energy_source'), type_='foreignkey')
        batch_op.drop_column('sub_region_id')
        batch_op.drop_column('region_id')
        batch_op.drop_column('energy_source_id')
        batch_op.drop_column('classification_id')

    op.drop_table('sub_region')
    op.drop_table('school_classification')
    op.drop_table('region')
    op.drop_table('electrical_energy_source')
    # ### end Alembic commands ###
