"""add question wizard fields

Revision ID: f4b99030859b
Revises: b7eeb4a32ab9
Create Date: 2026-02-04 17:19:19.932949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b99030859b'
down_revision = 'b7eeb4a32ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_descriptors',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('descriptor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['descriptor_id'], ['descriptor.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'descriptor_id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=32), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('descriptor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'descriptor', ['descriptor_id'], ['id'])
        batch_op.drop_column('type')

    op.drop_table('question_descriptors')
    # ### end Alembic commands ###
